/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RDICT_H_RPCGEN
#define _RDICT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXWORD 50
#define DICTSIZ 100

struct item {
	int id;
	char sn[MAXWORD];
	int stat;
};
typedef struct item item;

#define RDICTPROG 0x30090949
#define RDICTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INITW 1
extern  int * initw_1(void *, CLIENT *);
extern  int * initw_1_svc(void *, struct svc_req *);
#define INSERTW 2
extern  int * insertw_1(char **, CLIENT *);
extern  int * insertw_1_svc(char **, struct svc_req *);
#define DELETEW 3
extern  int * deletew_1(int *, CLIENT *);
extern  int * deletew_1_svc(int *, struct svc_req *);
#define LOOKUPW 4
extern  int * lookupw_1(char **, CLIENT *);
extern  int * lookupw_1_svc(char **, struct svc_req *);
#define LSW 5
extern  item * lsw_1(void *, CLIENT *);
extern  item * lsw_1_svc(void *, struct svc_req *);
#define SETW 6
extern  int * setw_1(int *, CLIENT *);
extern  int * setw_1_svc(int *, struct svc_req *);
extern int rdictprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INITW 1
extern  int * initw_1();
extern  int * initw_1_svc();
#define INSERTW 2
extern  int * insertw_1();
extern  int * insertw_1_svc();
#define DELETEW 3
extern  int * deletew_1();
extern  int * deletew_1_svc();
#define LOOKUPW 4
extern  int * lookupw_1();
extern  int * lookupw_1_svc();
#define LSW 5
extern  item * lsw_1();
extern  item * lsw_1_svc();
#define SETW 6
extern  int * setw_1();
extern  int * setw_1_svc();
extern int rdictprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_item (XDR *, item*);

#else /* K&R C */
extern bool_t xdr_item ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RDICT_H_RPCGEN */
